enhance(homepage): add TLF TradeMark Information
kubearmor/kubearmor.io pull request #45
Opened 2024-02-22 20:39 UTC by daemon1024

We need Linux Foundation TradeMark declaration on our website to comply with https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current/project-overview-page/best-practice-score/checks/legal-checks#trademark-disclaimer

2024-02-22 20:42 UTC, daemon1024 commented
This looks a bit big, any suggestions on what to styling class to use here?

2024-02-23 04:59 UTC, Aditya-150 requested changes
This should work I guess. Don't know how it will look on all screen sizes.

2024-02-23 04:59 UTC, Aditya-150 commented on src/components/HomepageSandbox/index.js
> +        <h4 className={styles.sandboxText}>
```suggestion
        <h4 className={styles.sandboxText} style={{ fontSize: "1rem" }}>
```

2024-02-23 05:06 UTC, Aditya-150 commented on src/components/HomepageSandbox/index.js
> +        <h4 className={styles.sandboxText}>
Pls check and let me know.
Otherwise we will have to write some more styles to fix it.

2024-03-27 06:48 UTC, Aditya-150 approved these changes

2024-03-27 06:49 UTC, merged